### ISSUE TITLE
Build steps can fail when services aren't ready

### ISSUE THREAD

**Issue by kevindew** [alphagov/govuk-docker#132]
Just jotting this down while it's fresh in my mind.

It's quite common for an application `build` to fail when dependencies haven't started fast enough. A couple of examples of this are: [build elasticsearch indexes](https://github.com/alphagov/govuk-docker/blob/faab3feabb168ce568fe080fe1a4501822d787ee/services/search-api/Makefile#L6) - elasticsearch seems to be a slow service to start, and [publishing routes](https://github.com/alphagov/govuk-docker/blob/faab3feabb168ce568fe080fe1a4501822d787ee/services/calendars/Makefile#L6) - Publishing API is often not ready.

A common approach to resolve this problem in the docker compose world are using a wait script, Docker itself doesn't provide a solution for [reasons](https://docs.docker.com/compose/startup-order/) which don't really apply to a setup. A couple of examples of the scripts are [wait-for-it](https://github.com/vishnubob/wait-for-it/issues/57) and [dockerize](https://github.com/jwilder/dockerize#waiting-for-other-dependencies). In the publishing-e2e-tests this is achieved with [compose healthchecks](https://docs.docker.com/compose/compose-file/#healthcheck) and [ruby loops](https://github.com/alphagov/publishing-e2e-tests/blob/0e0c3808e1ada4f53152b5e32179ae714f845357/lib/tasks/docker.rake).

**Comment by tijmenb** [comment]
Thanks! Moved to the Trello board to keep our backlog central: https://trello.com/c/YbvBZ4iq
