### ISSUE TITLE
`govuk-docker doctor` says "Dnsmasq not found"

### ISSUE THREAD

**Issue by ChrisBAshton** [alphagov/govuk-docker#140]
Running `govuk-docker doctor`:

```
❌ Dnsmasq not found.
You should install it with `brew install dnsmasq`.
For a manual installation, visit http://www.thekelleys.org.uk/dnsmasq/doc.html
```

But running `brew install dnsmasq`:

```                                                                                                                  
Warning: dnsmasq 2.80 is already installed and up-to-date
To reinstall 2.80, run `brew reinstall dnsmasq`
```

Dnsmasq is installed on my machine but not being found in the `doctor` check.

**Comment by thomasleese** [comment]
We saw a similar problem during development, can I confirm whether you have `/usr/local/sbin` in your `PATH`?

**Comment by ChrisBAshton** [comment]
It wasn't. Have now added it and it works 👍 

Will add that instruction to https://github.com/alphagov/govuk-docker/pull/141.

**Comment by thomasleese** [comment]
I think ideally we could find a way for the doctor command to find it even if you don’t have it in your path, because the service will still start without it being in your path.
