### ISSUE TITLE
Link-Checker-API not working inside Collections Publisher 

### ISSUE THREAD

**Issue by ChrisBAshton** [alphagov/govuk-docker#174]
![image](https://user-images.githubusercontent.com/5111927/63435652-355f9e80-c41f-11e9-8983-cce6abd214ec.png)

Inside `collections-publisher`:

```
govuk-docker startup e2e
```

Then navigate to http://collections-publisher.dev.gov.uk/step-by-step-pages and create or view a step by step and then click "Check for broken links"; we get a 503 error.

~This happens even if you run `govuk-docker startup` inside link-checker-api in another tab.~ As of https://github.com/alphagov/link-checker-api/pull/284, you can now have link-checker-api running in another tab and this is available to collections-publisher, fixing the issue. But we shouldn't have to do this - the `e2e` stack should account for the link-checker-api dependency and resolve it automatically.

**Comment by benthorner** [comment]
@ChrisBAshton I've tried this myself and it seems to work OK now, without any extra steps. I did have to pull the latest versions of the two repos in question.

![Screen Shot 2019-11-11 at 15 18 40](https://user-images.githubusercontent.com/9029009/68598408-a64ea980-0496-11ea-82b0-4186032e8a98.png)

**Comment by ChrisBAshton** [comment]
Thanks Ben. Yes I think this issue crops up now and again and required an image rebuild of the repos in question. Think I updated the govuk-docker readme to that effect, but forgot to close this issue. Closing now :)
