### ISSUE TITLE
DNS resolution strategy incompatible with Rails 6

### ISSUE THREAD

**Issue by ChrisBAshton** [alphagov/govuk-docker#176]
Arises from #174.

Applications running [Rails 6 have "Host Authorization" middleware](https://www.fngtps.com/2019/rails6-blocked-host/) to prevent against DNS rebinding attacks. This means that only requests from `0.0.0.0`, `::`, and `localhost` are allowed by default.

To get the custom alias domains (such as http://collections-publisher.dev.gov.uk/) to work, applications will either need to:

1. Explicitly add the local domain to its `config.hosts` (as has been done in [link-checker-api](https://github.com/alphagov/link-checker-api/pull/284)), or
2. Clear the entire whitelist (`config.hosts.clear`), preferably on local dev only. This lets through requests for all hostnames.

**Comment by issyl0** [comment]
Commenting on this so I get notifications about follow up. (I'm leading on Platform Health's "upgrade all the apps to Rails 6" mission this quarter.) Good spot! I'll add a card to our backlog to do this (or similar) for all our apps.

**Comment by benthorner** [comment]
For greater flexibility, I'm changing everything to do `config.hosts.clear` in development, which is perfectly safe and is less coupled to our particular domain. @issyl0 could you update the Platform Health card?

**Comment by issyl0** [comment]
This is great, thanks @benthorner!

**Comment by kevindew** [comment]
We think this will be resolved as all apps are now on Rails 6. Can reopen if not.
