### ISSUE TITLE
contacts-admin fails to build

### ISSUE THREAD

**Issue by huwd** [alphagov/govuk-docker#381]
## Steps to reproduce

`make contacts-admin`

## Stack trace

```
/home/huw/govuk/govuk-docker/exe/govuk-docker run contacts-admin-lite sh -c 'bin/rake db:migrate 2>/dev/null || bin/rake db:create db:migrate'
docker-compose -f [...] run contacts-admin-lite sh -c bin/rake db:migrate 2>/dev/null || bin/rake db:create db:migrate
Starting govuk-docker_mysql_1 ... done
Starting govuk-docker_redis_1 ... done
Database 'contacts_development' already exists
Database 'contacts_test' already exists
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateContacts < ActiveRecord::Migration[4.2]
/govuk/contacts-admin/db/migrate/20130814072057_create_contacts.rb:1:in `<main>'

Caused by:
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateContacts < ActiveRecord::Migration[4.2]
/govuk/contacts-admin/db/migrate/20130814072057_create_contacts.rb:1:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
make: *** [/home/huw/govuk/govuk-docker/projects/contacts-admin/Makefile:2: contacts-admin] Error 1
```

## Thoughts

Interesting, I would have thought this would have come up in the contacts app by now if this was failing, also seems that in whitehall we have classes that inherit from `ActiveRecord::Migration` without a version, and i don't think this error is occuring there... a red herring perhaps?

Can anyone else give this a go and verify this is happening for them too?

## Notes
 
Why was I running this?
`¯\_(ツ)_/¯` wanted to see what would happen if I ran `make all-apps`, this was one of the things that happened

**Comment by kevindew** [comment]
Ooh good catch, the problem we've got here is that contacts-admin is setting up the initial db by running migrations which isn't [the recommended approach for building the db of a Rails app](https://guides.rubyonrails.org/v3.2/migrations.html#schema-dumping-and-you). If we switch that to `db:setup` that will make this app [consistent with Whitehall and others](https://github.com/alphagov/govuk-docker/blob/a9e00d16c613f42159897ea003e20b9ff3769c3e/projects/whitehall/Makefile#L2) and likely resolve your problem.

This then ties into a perpetually deferred decision about what to do about old migrations that can stay around like little landmines waiting to ruin someones day. This came up recently [with signon](https://github.com/alphagov/signon/pull/1458) and was a little contentious.

**Comment by huwd** [comment]
Ah thatnks! That's really helpful.
Just testing now. Will have a PR up shortly.
