### ISSUE TITLE
GDS API Adapters fails to build

### ISSUE THREAD

**Issue by huwd** [alphagov/govuk-docker#389]
In this episode of `Will it build`:

# Steps to reproduce

Join our plucky cast as they attempt to run:
`make gds-api-adapters`

## Stack trace

And encounter the mysterious case of the missing Argument 

```
/home/huw/govuk/govuk-docker/exe/govuk-docker run gds-api-adapters-lite rbenv install -s || (/home/huw/govuk/govuk-docker/exe/govuk-docker build --no-cache gds-api-adapters-lite; /home/huw/govuk/govuk-docker/exe/govuk-docker run gds-api-adapters-lite rbenv install -s)
docker-compose -f [...] run gds-api-adapters-lite rbenv install -s
/home/huw/govuk/govuk-docker/exe/govuk-docker run gds-api-adapters-lite sh -c 'gem install --conservative --no-document bundler -v $(grep -A1 "BUNDLED WITH" Gemfile.lock | tail -1)'
docker-compose -f [...] run gds-api-adapters-lite sh -c gem install --conservative --no-document bundler -v $(grep -A1 "BUNDLED WITH" Gemfile.lock | tail -1)
grep: Gemfile.lock: No such file or directory
ERROR:  While executing gem ... (OptionParser::MissingArgument)
    missing argument: -v
make: *** [Makefile:41: bundle-gds-api-adapters] Error 1
```

## Also note

So... I suspect this is because the central `Makefile` [has an expectation there'll be a Gemfile.lock coming with each package](https://github.com/alphagov/govuk-docker/blob/master/Makefile#L41).
But in this case gds-api-adapters appears to be a gem itself.

So i guess in this case something more custom in the makefile, (or perhaps another task that focuses on the steps for Gems?) is the route?

**Comment by kevindew** [comment]
Oh interesting, I guess that happens with most gems since they'll often not have a Gemfile.lock on initial cloning. I guess the options we'd want to consider is either only running `gem install bundler` when Gemfile.lock exists or to just install the latest version of bundler in that scenario. I think the former situation should be fine since Ruby bundles bundler in recent versions. Do you know if this commands works for you if you just comment out that line?

**Comment by huwd** [comment]
Yep that works great if i comment that out.
So... humm we could either wrap this in an If statement, so IF there's a Gemfile.lock then run this command?
Or is there a more graceful failure state? Like if you run it and fail then continue?

my bash fu is a little lacking, if you had any starting point on syntax i'd be happy to go test until there's something PR-able?

**Comment by huwd** [comment]
Humm or... perhaps we _should_ have the assumption that every repo should have a `Gemfile.lock` - unless it has a gemspec file?

**Comment by kevindew** [comment]
Sure, for lack of a more elegant idea this should do the trick: `if [ -f Gemfile.lock ]; then gem install --conservative --no-document bundler -v $$(grep -A1 "BUNDLED WITH" Gemfile.lock | tail -1); fi`

It feels somewhat more complex to involve gemspecs in the equation if we can avoid it

**Comment by huwd** [comment]
Sorry had some time off and only just got back on this!
https://github.com/alphagov/govuk-docker/compare/fix-gds-api-adapters?expand=1
