### ISSUE TITLE
Bouncer will not build

### ISSUE THREAD

**Issue by huwd** [alphagov/govuk-docker#404]
# Steps to reproduce

`make bouncher`

## Stack trace

Some kind of issue in the DB setup perhaps... 

```
dropdb --if-exists transition_test
dropdb: could not connect to database template1: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
rake aborted!
Command failed with status (1): [dropdb --if-exists transition_test...]
/govuk/bouncer/Rakefile:11:in `block (2 levels) in <top (required)>'
/home/build/.rbenv/versions/2.6.6/bin/bundle:23:in `load'
/home/build/.rbenv/versions/2.6.6/bin/bundle:23:in `<main>'
Tasks: TOP => db:reset
(See full trace by running task with --trace)
make: *** [/home/huw/govuk/govuk-docker/projects/bouncer/Makefile:2: bouncer] Error 1

```

It appears to be [this line ](https://github.com/alphagov/govuk-docker/blob/master/projects/bouncer/Makefile#L2)that is causing the issue:
`govuk-docker run bouncer-lite sh -c 'bundle exec rake db:reset'`

Would be good if someone else can confirm this is reproducable on their machine and not some wierd artifact of some database containers I might not have cleared out?

**Comment by huwd** [comment]
@benthorner [I've been going back through the commits,](https://github.com/alphagov/govuk-docker/commit/8caac40e93c4e3db66a513540f5e097fb02f126d) do you recall why it's important to try and do a db:reset here?

**Comment by benthorner** [comment]
@huwd indeed I do - I could have been more helpful in my commit message. I'm surprised this is failing, though, since I added it recently - have you tried pulling the latest codebase?

As the explanation: Bouncer [is special/awful](https://github.com/alphagov/bouncer/blob/master/Rakefile#L10); it defines its own DB tasks, as opposed to the ones we're used to.

**Comment by huwd** [comment]
I think i did... let me just double check - would you have a chance to quickly nip into your `govuk-docker` folder and run `make bouncer` to see if it's not just me?

**Comment by huwd** [comment]
yep so I'm running bouncer wtih the latest commit:
`Wed Sep 30 16:32:00 2020 +0100 8c644a3`

**Comment by huwd** [comment]
> As the explanation: Bouncer is special/awful; it defines its own DB tasks, as opposed to the ones we're used to.

Right that makes a lot more sense, thanks very much.
So this _should_ be running, let me see if I can get this to run outside of docker, then trace it back...

**Comment by huwd** [comment]
`bundle exec rake db:reset` works outside of docker, so I'm thinking this must be to do with the postgres connection

**Comment by benthorner** [comment]
Turns out my supporting PR never got approved. Would you like to review it?

https://github.com/alphagov/bouncer/pull/265

**Comment by huwd** [comment]
Ah ha! Have taken a look over and approved it

**Comment by benthorner** [comment]
Thanks @huwd - does that conclude this issue for you?

**Comment by huwd** [comment]
Ace yeah now that's merged will close this,
Cheers!
