### ISSUE TITLE
Generic Ruby Library will not build (and shouldn't try to!)

### ISSUE THREAD

**Issue by huwd** [alphagov/govuk-docker#407]
## Steps to reproduce

`make all-apps`

## Issue

[We've talked about removing all-apps in the past.](https://github.com/alphagov/govuk-docker/issues/384#issuecomment-669862676)
It currently tries to build the following list:
```
asset-manager authenticating-proxy cache-clearing-service calculators collections collections-publisher contacts-admin content-data-admin content-data-api content-publisher content-store content-tagger datagovuk_publish email-alert-api email-alert-frontend email-alert-service feedback finder-frontend frontend generic-ruby-library government-frontend govuk_crawler_worker govuk-developer-docs govuk_publishing_components hmrc-manuals-api imminence info-frontend licence-finder link-checker-api local-links-manager manuals-frontend manuals-publisher mapit maslow miller-columns-element publisher publishing-api release router-api router search-admin search-api service-manual-frontend service-manual-publisher short-url-manager signon smart-answers specialist-publisher special-route-publisher static support-api support transition travel-advice-publisher whitehall
```

So it will try and build generic-ruby-library.

However running `make generic-ruby-library` fails because the makefile there has a set of more specifc rules.

## Solution

We should remove `all-apps` or ensure that it does not include `generic-ruby-library` or provide a separate make step to cover everything in that makefile.

NB: This also means that the five generic ruby files do not appear in ALL_APPS, if we're trying to test builds that way.

**Comment by benthorner** [comment]
Oops, the `all-apps` does get rather sidelined.

I think your suggestion to remove it is pragmatic: the only use case for it is the project you're working on at the moment, but that can easily be replicated by manually working through all the projects and running `make <project>` for each.

Would you like to raise a PR to remove it?

**Comment by huwd** [comment]
on it
