### ISSUE TITLE
Make Pull doesn't work for generic-ruby-libraries or main branches

### ISSUE THREAD

**Issue by huwd** [alphagov/govuk-docker#420]
## Describe the issue

To reproduce run:
`make pull`

For generic-ruby-library you now get:
`generic-ruby-library                      directory not found `

Also for any repository using `main` over `master` it will fail.

## Expected behaviour

Ideally it would follow up with generic-ruby-libaries and clone all those separately.
It's still important those codebases are up to date i think.

GDS has committed to switching from `master` to main` in all our repositories, we should prep for that change or allow both.

**Comment by benthorner** [comment]
Oh dear, another casualty of my (ahem) refactoring. That said, I also think it's a bit of [a pointless task](https://github.com/alphagov/govuk-docker#how-to-update-everything): it seldom works unless you've not switched to a branch on any repos. What do you think about just removing it (and `clone`)?

**Comment by benthorner** [comment]
(I was also considering whether we should revert [my refactoring](https://github.com/alphagov/govuk-docker/pull/401). We could still do this if it's causing unavoidable pain - e.g. if we want to keep these `make` tasks - as it does deviate from the pattern of a "project".)
