### ISSUE TITLE
Documentation error in README.md?

### ISSUE THREAD

**Issue by KludgeKML** [alphagov/govuk-docker#562]
https://github.com/alphagov/govuk-docker/blob/main/README.md?plain=1#L93

appears to not be how the cli works now. 

It says that you need to put in the name of the app when using the up command

`govuk-docker-up imminence-app`

...but for the apps I've tried so far (imminence, feedback) appear to automatically supply the app name, so doing it that way fails (it tries to bring up imminence-imminence-app). What works is:

`govuk-docker-up app`

**Comment by injms** [comment]
There's a subtle difference between the command in the documentation and the command you've mentioned - the dash between the `govuk-docker` and the `up` is quite a trip hazard:

```
govuk-docker up imminence-app
govuk-docker-up app
```

The dashless command requires the name of the app, and the command with a dash does not (as long as you run it inside the correct folder).

Can you try running `govuk-docker up imminence-app` and compare it to running `govuk-docker-up app` inside the imminence folder?

**Comment by KludgeKML** [comment]
Ah, okay. Yes, that - does alter the behaviour. It's a bit of a principle of least astonishment test case, but that does make the documentation right, and it would probably be dangerous to all existing users to try to change the behaviour, so I'll close this.

Thanks!
